### ISSUE TITLE
Epic: Treffliste/Treffboks

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#491]
### Feature beskrivelse

GUI + logikk: disse issuene dekker en treffboks som vises i bildet under. Boksen skal lages og fylles med treffinformasjon som ble produsert på et tidligere steg under søk. Anta at søk er laget og bruk gjerne dummy data hvis søk ikke er implementert ennå.

- [x] Informasjonsforvaltning/concept-catalog-gui#476
- [x] Informasjonsforvaltning/concept-catalog-gui#475
- [x] Informasjonsforvaltning/concept-catalog-gui#474
- [x] Informasjonsforvaltning/concept-catalog-gui#473
- [x] Legge til "Publisert i Felles Datakatalog", isPublished -> boolean fra backend (ikke klart i backend enda). Dersom boolean er false skal det ikke stå noe.

- [x] Legge til hasRevision
- [x] Informasjonsforvaltning/catalog-frontend#279

Bilde:
<img width="841" alt="image" src="https://github.com/Informasjonsforvaltning/concept-catalog-gui/assets/48259307/c1833ae8-6698-4c41-88f8-ef9046beed50">
Lenke til skisse:  
https://www.figma.com/file/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?node-id=24-26892&t=O7QMYyIMX1sqDR74-0

### Hvorfor trenger vi det?
Lenke til brukerhistorie:
https://github.com/Informasjonsforvaltning/behov/issues/806 

### Forslag/løsning [Valgfritt]
sjekk om dette er løst et annet sted og om noe kan gjenbrukes, ellers "be creativ"!

### Definisjon av ferdig
?

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by AinaEngen** [comment]
Delvis ferdig, men venter på at kodelistene blir implementert (breadcrumbs), merkelapp og evt. chip

**Comment by KjerstiSteien** [comment]
@hegeaal kan denne regnes som ferdig nå?

**Comment by hegeaal** [comment]
> @hegeaal kan denne regnes som ferdig nå?

Jeg er litt usikker, for meg ser det ut som at det meste er på plass.

Slik 👇 ser det ut per nå, så kan ikke se noe som mangler, evt. bare at under revidering og tidelt ikke har samme hjelpetekst og plassering. Vet ikke om det er gjort med vilje?

![image](https://github.com/Informasjonsforvaltning/concept-catalog-gui/assets/48259307/4ad9493b-1319-40d1-b397-620a16cfc86a)

![image](https://github.com/Informasjonsforvaltning/concept-catalog-gui/assets/48259307/be93c440-912d-4fd9-9370-3b7fffe581c3)

**Comment by AinaEngen** [comment]
@matfuru
