### ISSUE TITLE
Epic: Sidebar

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#492]
### Feature beskrivelse
- [x] Informasjonsforvaltning/concept-catalog-gui#527
- [x] Informasjonsforvaltning/concept-catalog-gui#480
- [ ] Informasjonsforvaltning/concept-catalog-gui#479 (skal ikke med i filterbar. Se kommentar i saken)
- [x] Informasjonsforvaltning/catalog-frontend#106
- [x] Informasjonsforvaltning/concept-catalog-gui#505
- [x] Informasjonsforvaltning/concept-catalog-gui#506
- [x] Informasjonsforvaltning/concept-catalog-gui#515
- [x] Informasjonsforvaltning/concept-catalog-gui#516

Bilde:
![image](https://user-images.githubusercontent.com/50879748/219083641-57856175-678c-4a0d-a4a1-ea803d84b99f.png)

Lenke til skisse:  
https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159%3A41103&viewport=520%2C695%2C0.5&scaling=scale-down-width

### Hvorfor trenger vi det?
Lenke til brukerhistorie:
https://github.com/Informasjonsforvaltning/behov/issues/806 

### Forslag/løsning [Valgfritt]
sjekk om dette er løst et annet sted og om noe kan gjenbrukes, ellers "be creativ"!

### Definisjon av ferdig
?

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Mangler: Egenskapsnavn og forretningsbegrep. Oppdaterte skisser kommer.

**Comment by pooriamehregan** [comment]
Jeg mener det er mulig å justere disse innstillingene i adminpanelet, ihvertfall front-end. Enig i at design og implementasjon bør diskuteres.

**Comment by KjerstiSteien** [comment]
Jeg er ikke sikker på om vi kommer til å løse dette i admin i første omgang. Virker utfordrende å løse. Mulig vi hardkoder de to filtrene for Skatt. La oss ta en prat om det.

**Comment by KjerstiSteien** [comment]
Vi ønsker at filtrene skal være default lukket.
