### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#500]
- [x] Informasjonsforvaltning/catalog-frontend#3
- [x] Informasjonsforvaltning/catalog-frontend#2
- [x] Informasjonsforvaltning/catalog-frontend#5
